### ISSUE TITLE
可能文字有误

### ISSUE THREAD

**Issue by zsy-cn** [phodal/clean-angular#12]
写的很好，我们前端引入框架，越来越复杂，现在也在找处理办法

https://github.com/phodal/clean-frontend#全功能团队

过去，我在 ThoughtWorks 的某个团队里，采用的是全功能团队的模式——团队成员擅长某一领域，但是会其它领域，比如擅长前端，`后点后端`。它可以在某种程度上，降低沟通成本。而这意味着，我们有大量的 knowledge transfer 的成本。因此，我们采用了结对编程、让新人讲项目相关的 session。

`后点后端` 是不是 `会点后端` ？

**Comment by phodal** [comment]
是的，欢迎来 PR
