### ISSUE TITLE
clean-architecture+domain 垂直分层问题

### ISSUE THREAD

**Issue by xukaijie111** [phodal/clean-angular#19]
你好，有个问题请教下:

当使用domain垂直分层的时候，每个domain 相当于redux的结构。对于单个usecase的执行是没问题。但是当用户的一个操作涉及到多个usecase组合的时候，这部分逻辑放在哪里进行呢，例如：用户点击加购物车，弹出领券，领券后，加到用户中心，然后自动将商品加到购物车。这里面涉及劵，用户，购物车多个domain。在哪层完成这些逻辑的组合呢

**Comment by phodal** [comment]
向上提一层 application
